version: '3.0'

services:
  localstack:
    privileged: true
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "4574:4574"
      - "4581:4581"
      - "8080:8080"
    environment:
      - DEBUG=1
      - SERVICES=s3:4572,lambda:4574,cloudformation:4581
      - DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=Woo
      - AWS_ACCESS_KEY_ID=Hoo
      - AWS_DEFAULT_OUTPUT=json
      - AWS_DEFAULT_REGION=us-east-1
      # Based on an error from Localstack: Note that Node.js and .NET Core Lambdas currently require LAMBDA_EXECUTOR=docker
      - LAMBDA_EXECUTOR=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
