version: '3.0'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4568:4568"
      - "4572:4572"
      - "4575:4575"
      - "4576:4576"
      - "4581:4581"
      - "8080:8080"
    environment:
      - DEBUG=1
      - SERVICES=kinesis:4568,s3:4572,sns:4575,sqs:4576,cloudformation:4581
      - DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=Woo
      - AWS_ACCESS_KEY_ID=Hoo
      - AWS_DEFAULT_OUTPUT=json
      - AWS_DEFAULT_REGION=us-east-1
